const CONFIG = {
    introTitle: 'Eyeu eyyyyyyyyyyyyyyy',
    introDesc: `Anh chỉ muốn nói là anh yêu em nhiều lammmmmmmmmmmmm ạ.`,
    btnIntro: 'hoho',
    title: 'Dm anh muốn hun em, muonnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn hunnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.',
    desc: 'À anh cũng muốn đc ôm nữaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa hic =((. ',
    btnYes: 'Yêu anh lắm ạ.',
    btnNo: 'Bấm nút này đấm cho mấy phát.',
    question:'Tell me the reason why u love me :33',
    btnReply: 'Tell meeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.',
    reply: 'Tại vì anh dth vãi loz. ',
    mess: 'Xời đc khen ngại quéeeeeeeeeeeeeeeeeeeee hì.',
    messDesc: 'Sức chịu đựng của anh có giới thiệu cho nên là vào học lại coi chừng có con lợn bị đè xuống hunn',
    btnAccept: 'Hoho =}}',
